name: chainmail
description: Enhance productivity and readability with mixin based widget extensions.
version: 0.0.1
repository: https://github.com/helightdev/chainmail

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: {}
